name: pymandelbrot
version: '1.2'
summary: Mandelbrot Drawer
description: |
  Mandelbrot drawer draws the Mandelbrot set for you.
confinement: strict 
base: core18
grade: stable
#icon: ${SNAP}/meta/gui/pymandelbrot.png

parts:
  pymandelbrot:
    plugin: python
#    plugin: meson
#    meson-parameters: [--prefix=/snap/craig-warner/current/usr]
#    override-pull: |
#      snapcraftctl pull
#
#      sed -i.bak -e 's|Icon=com.github.craig-warner.pymandelbrot|Icon=/usr/share/icons/hicolor/scalable/apps/com.github.craig-warner.pymandelbrot.svg|g' data/com.github.craig-warner.pymandelbrot.desktop.in
    python-version: python3
    source-branch: master 
    source: https://github.com/craig-warner/pymandelbrot.git
    python-packages: [tk] 
    stage-packages: [python3-tk, python-six]

layout:
  /usr/share/tcltk:
    bind: $SNAP/usr/share/tcltk
  /usr/lib/tcltk:
    bind: $SNAP/usr/lib/tcltk

#apps:
#  pymandelbrot:
#    command: bin/pymandelbrot
#    plugs: ['desktop', 'framebuffer', 'camera', 'network', 'home', 'opengl', 'x11']

apps:
  pymandelbrot:
    command: pymandelbrot
#    command: desktop-launch $SNAP/usr/bin/com.github.craig-warner.pymandelbrot
    desktop: snap/gui/pymandelbrot.desktop
    plugs:
      - desktop
      - desktop-legacy